// src/components/DynamicChart.jsx
import React, { useState, useEffect, useRef, useCallback } from "react";
import * as TWEEN from "@tweenjs/tween.js";
import Shuffle from "shufflejs";
import BarWithImageLeft from "./BarWithImageLeft";
import Scale from "./Scale";
import { stats } from "../data/result";
import { labelInfo } from "../data/indiaInfo";
import "./DynamicChart.css";

const DynamicChart = ({
  barType = "barWithImageLeft",
  interval = 2000,
  limit = 15,
  shuffleSpeed = 1000,
  stats,
  labelInfo,
  date,
  fixed = 0,
  scale = 500000000,
  maximum = 0,
  dynamic = false,
  unit = "",
  tweening = true,
  additional = false,
  additionalLimit = 0,
  additionalTitle = "",
  additionalStats = [],
  additionalUnit = "",
  additionalCand = []
}) => {
  const [barList, setBarList] = useState([]);
  const [scaleList, setScaleList] = useState([]);
  const [scaleUnit, setScaleUnit] = useState(scale);
  const [nullNumber] = useState(0);
  const [representativeImg, setRepresentativeImg] = useState("");
  const [year, setYear] = useState(0);
  const [progress, setProgress] = useState(1);
  const [barDict, setBarDict] = useState({});

  const containerRef = useRef(null);
  const instanceRef = useRef(null);
  const animationRef = useRef(null);

  const progressWidth = `${progress * 100}%`;

  // Setup animation loop with a more robust animation frame handler
  useEffect(() => {
    let animationFrameId;

    function animate(time) {
      animationFrameId = requestAnimationFrame(animate);
      TWEEN.update(time);
    }

    animationFrameId = requestAnimationFrame(animate);

    return () => {
      // Clean up animation frame on unmount
      cancelAnimationFrame(animationFrameId);
    };
  }, []);

  const charToNum = str => {
    let ret = 0;
    for (let i = 0; i < Math.max(str.length, 5); i++) {
      ret +=
        (100 - (str.charCodeAt(i) - " ".charCodeAt(0))) / Math.pow(100, i + 1);
    }
    return ret;
  };

  const getBarValue = useCallback(
    element => {
      const label = element.id.slice(8);
      if (barDict[label]) {
        return barDict[label].value + charToNum(label);
      } else {
        console.log(label);
        console.log(barDict);
        return 0;
      }
    },
    [barDict]
  );

  const getWidth = useCallback(
    (cur, max, min = 0) => {
      const maximumValue = Math.max(max, maximum);
      const offset = 0.1;
      const frontWidth = 0.7;
      const backWidth = 0.2;
      if (dynamic)
        return (
          (offset +
            ((cur - min) / (max - min)) * frontWidth +
            (cur / maximumValue) * backWidth) *
          75
        );
      else
        return (
          (offset +
            (cur / max) * frontWidth +
            (cur / maximumValue) * backWidth) *
          75
        );
    },
    [maximum, dynamic]
  );

  // Define function references to break circular dependencies
  const adjustWidthRef = useRef(null);
  const adjustScaleRef = useRef(null);

  const adjustWidth = useCallback(
    (bars, max, min) => {
      for (const [i, v] of bars.entries()) {
        if (i < limit) {
          const width = getWidth(v.value, max, min);
          if (v.value === parseInt(v.value.toString())) v.value += 0.0001;
          v.ref?.current?.visible();
          v.ref?.current?.setWidth(width + "vw");
        } else {
          v.ref?.current?.invisible();
        }
      }
    },
    [limit, getWidth]
  );

  // Store function in ref
  adjustWidthRef.current = adjustWidth;

  const adjustScale = useCallback(
    (max, min) => {
      setScaleList(prevScaleList => {
        let newScaleList = [...prevScaleList];
        const start = newScaleList.length
          ? newScaleList[newScaleList.length - 1].value + scaleUnit
          : scaleUnit;

        for (let value = start; value < max * 1.1; value += scaleUnit) {
          newScaleList.push({
            value: value,
            left: 0
          });
        }

        const cnt = newScaleList.length;
        if (cnt > 8) {
          setScaleUnit(scaleUnit * 2);
          newScaleList = newScaleList.filter((_, i) => (i & 1) === 0);
        } else if (cnt < 4) {
          const newUnit = Math.round(scaleUnit / 2);
          setScaleUnit(newUnit);
          newScaleList = newScaleList.concat(
            newScaleList.map(v => ({
              value: v.value - newUnit,
              left: 0
            }))
          );
        }

        newScaleList = newScaleList.filter(
          v => min <= v.value && v.value <= max
        );

        for (const scale of newScaleList) {
          scale.left = getWidth(scale.value, max, min);
        }

        return newScaleList;
      });
    },
    [scaleUnit, getWidth]
  );

  // Store function in ref
  adjustScaleRef.current = adjustScale;

  const adjustChart = useCallback(() => {
    const bars = Object.values(barDict).sort((v1, v2) => {
      return v2.value + charToNum(v2.label) - (v1.value + charToNum(v1.label));
    });
    if (bars.length > 0) {
      const top = bars[0];
      const max = top.value;
      const min =
        dynamic && bars.length >= limit ? bars[limit - 1].value * 0.9 : 0;

      setRepresentativeImg(top.img);
      if (adjustWidthRef.current) adjustWidthRef.current(bars, max, min);
      if (adjustScaleRef.current) adjustScaleRef.current(max, min);
    }
  }, [barDict, dynamic, limit, charToNum]);

  const createBar = useCallback(
    data => {
      const value = parseFloat(data.value);
      if (!isNaN(value)) {
        const { color, img } = getBarLabelInfo(data);
        const bar = {
          label: data.label,
          value: value,
          color: color || "#000",
          img: img || "",
          size: 10,
          fixed: fixed,
          team: data.team,
          ref: React.createRef()
        };
        return bar;
      }
      return null;
    },
    [fixed]
  );

  const getBarLabelInfo = useCallback(
    data => {
      if (data.team) {
        const info = labelInfo[data.team];
        if (info) return info;
      }
      if (data.label) {
        const info = labelInfo[data.label];
        if (info) return info;
      }
      return { color: "#000", img: "" };
    },
    [labelInfo]
  );

  const sortNodeBar = useCallback(() => {
    if (instanceRef.current && containerRef.current) {
      instanceRef.current.sort({
        by: element => {
          return getBarValue(element);
        },
        reverse: true
      });
    }
  }, [getBarValue]);

  const getBarObject = useCallback(
    label => {
      return barList.find(bar => bar.label === label);
    },
    [barList]
  );

  // Use a ref to track if initialization has run
  const hasInitialized = useRef(false);

  useEffect(() => {
    // Only run initialization once
    if (hasInitialized.current) return;
    hasInitialized.current = true;

    if (containerRef.current) {
      instanceRef.current = new Shuffle(containerRef.current, {
        itemSelector: ".item",
        speed: shuffleSpeed
      });
    }

    // Set initial data
    setYear(parseInt(date[0]));
    const initialBars = [];
    const initialBarDict = {};

    if (stats && stats[0]) {
      for (const i in stats[0]) {
        const curData = { ...stats[0][i] }; // Create a copy to avoid mutating original data
        curData.value = Number(curData.value).toString();
        const bar = createBar(curData);
        if (bar) {
          initialBars.push(bar);
          initialBarDict[bar.label] = bar;
        }
      }
    }

    setBarList(initialBars);
    setBarDict(initialBarDict);

    // Start animation after initial setup
    const initTimeout = setTimeout(() => {
      let index = 1;
      let currentBarDict = { ...initialBarDict };

      const startTimeout = setTimeout(() => {
        const loop = setInterval(() => {
          if (stats && index < stats.length) {
            setYear(parseInt(date[index]));
            const before = {};
            const after = {};

            for (const [i, stat] of stats[index].entries()) {
              if (i >= 10) break; // Limit to top 10 items for performance

              let prevData = currentBarDict[stat.label];
              if (!prevData) {
                const newBar = createBar({
                  label: stat.label,
                  value: nullNumber.toString(),
                  team: stat.team
                });
                if (newBar) {
                  currentBarDict[stat.label] = newBar;
                  setBarList(prev => [...prev, newBar]);
                  prevData = newBar;
                }
              }
              if (prevData) {
                before[stat.label] = parseFloat(prevData.value) || 0;
                after[stat.label] = parseFloat(stat.value) || 0;
              }
            }

            // Animation tween
            if (tweening && Object.keys(before).length > 0) {
              // Clear any existing animation
              if (animationRef.current) {
                animationRef.current.stop();
              }

              before["progress"] = progress;
              after["progress"] = 1;

              const tween = new TWEEN.Tween(before)
                .to(after, interval * 0.8)
                .easing(TWEEN.Easing.Quadratic.Out)
                .onUpdate(obj => {
                  setProgress(obj.progress || 0);

                  // Update bar values directly in the dict
                  for (const label in obj) {
                    if (label !== "progress" && currentBarDict[label]) {
                      currentBarDict[label].value = obj[label];
                    }
                  }

                  // Update state with new values
                  setBarDict({ ...currentBarDict });
                })
                .start();

              animationRef.current = tween;
            } else {
              // Instant update without animation
              for (const label in after) {
                if (currentBarDict[label]) {
                  currentBarDict[label].value = after[label];
                }
              }
              setBarDict({ ...currentBarDict });
              setProgress(1);
            }

            index++;
          } else {
            clearInterval(loop);
          }
        }, interval);
      }, 1000);

      return () => {
        clearTimeout(startTimeout);
        clearInterval(loop);
      };
    }, 500);

    return () => {
      clearTimeout(initTimeout);
      if (instanceRef.current) {
        instanceRef.current.destroy();
        instanceRef.current = null;
      }
    };
  }, []); // Empty dependency array to run only once

  // Separate effect for handling chart adjustments when barDict changes
  useEffect(() => {
    if (Object.keys(barDict).length > 0) {
      // Use a timeout to batch updates and avoid excessive re-renders
      const adjustTimeout = setTimeout(() => {
        adjustChart();
        if (instanceRef.current && containerRef.current) {
          instanceRef.current.sort({
            by: element => {
              return getBarValue(element);
            },
            reverse: true
          });
        }
      }, 50);

      return () => clearTimeout(adjustTimeout);
    }
  }, [barDict, adjustChart, getBarValue]);

  return (
    <div id="wrapper">
      {scaleList.map((scale, i) => (
        <Scale
          key={`scale${i}`}
          value={scale.value}
          left={scale.left}
          unit={unit}
          margin={15.3}
          fixed={fixed}
        />
      ))}
      <div
        ref={containerRef}
        id="container"
        className="item-container"
        style={{ height: "500px", overflow: "visible" }}
      >
        {barType === "barWithImageLeft" &&
          barList.map((bar, i) => (
            <BarWithImageLeft
              key={i}
              ref={bar.ref}
              color={bar.color}
              img={bar.img}
              size={bar.size}
              label={bar.label}
              value={bar.value}
              unit={unit}
              team={bar.team}
              fixed={bar.fixed}
            />
          ))}
      </div>
      <div id="year" className="year">
        <div>{year}</div>
        <div className="progress" style={{ width: progressWidth }}></div>
      </div>
      <div
        className="representative"
        style={{ backgroundImage: `url(${representativeImg})` }}
      ></div>
      {additional && (
        <div className="additional">
          <table>
            <thead>
              <tr>
                <th>{additionalTitle}</th>
              </tr>
            </thead>
            <tbody id="additional-info"></tbody>
          </table>
        </div>
      )}
    </div>
  );
};

export default DynamicChart;

// cho-bar-chart/src/components/DynamicChart.vue
<template>
  <div id="wrapper">
    <scale
      v-for="(scale, i) in scaleList"
      :key="'scale' + i"
      v-bind="scale"
      v-bind:unit="unit"
      v-bind:margin="15.3"
    ></scale>
    <div
      id="container"
      class="item-container"
      style="height: 500px; overflow: visible"
    >
      <barWithImageLeft
        v-if="barType === 'barWithImageLeft'"
        v-for="(bar, i) in barList"
        :key="i"
        v-bind="bar"
        :unit="unit"
      ></barWithImageLeft>
    </div>
    <div id="year" class="year">
      <div>{{ year }}</div>
      <div class="progress" v-bind:style="{ width: progressWidth }"></div>
    </div>
    <div
      class="representative"
      v-bind:style="{ 'background-image': 'url(' + representativeImg + ')' }"
    ></div>
    <div class="additional">
      <table>
        <thead>
          <tr>
            <th>{{ additionalTitle }}</th>
          </tr>
        </thead>
        <tbody id="additional-info"></tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUpdated, nextTick } from "vue";
import Shuffle from "shufflejs";
import TWEEN from "tween.js";
import barWithImageLeft from "./BarWithImageLeft.vue";
import scale from "./Scale.vue";

// Setup the animation loop.
function animate(time) {
  requestAnimationFrame(animate);
  TWEEN.update(time);
}
requestAnimationFrame(animate);

// Props
const props = defineProps({
  barType: {
    type: String,
    default: "barWithImageLeft",
    validator: function(value) {
      return ["barWithImageLeft"].indexOf(value) !== -1;
    }
  },
  interval: {
    type: Number,
    default: 2 * 1000
  },
  limit: {
    type: Number,
    default: 15
  },
  shuffleSpeed: {
    type: Number,
    default: 1000
  },
  stats: {
    type: Array
  },
  labelInfo: {
    type: Object
  },
  date: {
    type: Array
  },
  fixed: {
    type: Number,
    default: 0
  },
  scale: {
    type: Number,
    default: 500000000
  },
  maximum: {
    type: Number,
    default: 0
  },
  dynamic: {
    type: Boolean,
    default: false
  },
  unit: {
    type: String,
    default: ""
  },
  tweening: {
    type: Boolean,
    default: true
  },
  additional: {
    type: Boolean,
    default: false
  },
  additionalLimit: {
    type: Number,
    default: 0
  },
  additionalTitle: {
    type: String,
    default: ""
  },
  additionalStats: {
    type: Array,
    default: () => []
  },
  additionalUnit: {
    type: String,
    default: ""
  },
  additionalCand: {
    type: Array,
    default: () => []
  }
});

// Reactive data
const barList = ref([]);
const instance = ref(null);
const scaleList = ref([]);
const scaleUnit = ref(props.scale);
const nullNumber = ref(0);
const representativeImg = ref("");
const year = ref(0);
const progress = ref(1);
const barDict = ref({});

// Computed properties
const progressWidth = computed(() => {
  return progress.value * 100 + "%";
});

// Methods
const charToNum = str => {
  let ret = 0;
  for (let i = 0; i < Math.max(str.length, 5); i++) {
    ret += (100 - (str.charCodeAt(i) - " ".charCodeAt(0))) / 100 ** (i + 1);
  }
  return ret;
};

const getBarValue = element => {
  const label = element.id.slice(8);
  if (barDict.value[label]) {
    return barDict.value[label].value + charToNum(label);
  } else {
    console.log(label);
    console.log(barDict.value);
    return 0;
  }
};

const getWidth = (cur, max, min = 0) => {
  const maximum = Math.max(max, props.maximum);
  const offset = 0.1;
  const frontWidth = 0.7;
  const backWidth = 0.2;
  if (props.dynamic)
    return (
      (offset +
        ((cur - min) / (max - min)) * frontWidth +
        (cur / maximum) * backWidth) *
      75
    );
  else
    return (
      (offset + (cur / max) * frontWidth + (cur / maximum) * backWidth) * 75
    );
};

const adjustChart = () => {
  const bars = Object.values(barDict.value).sort((v1, v2) => {
    return v2.value + charToNum(v2.label) - (v1.value + charToNum(v1.label));
  });
  if (bars.length > 0) {
    const top = bars[0];
    const max = top.value;
    const min =
      props.dynamic && bars.length >= props.limit
        ? bars[props.limit - 1].value * 0.9
        : 0;

    representativeImg.value = top.img;
    adjustWidth(bars, max, min);
    adjustScale(max, min);
  }
};

const adjustWidth = (bars, max, min) => {
  for (const [i, v] of bars.entries()) {
    if (i < props.limit) {
      const width = getWidth(v.value, max, min);
      const dict = getBarObject(v.label);
      if (dict.value === parseInt(dict.value)) dict.value += 0.0001;
      v.visible();
      v.setWidth(width + "vw");
    } else {
      v.invisible();
    }
  }
};

const adjustScale = (max, min) => {
  const start = scaleList.value.length
    ? scaleList.value[scaleList.value.length - 1].value + scaleUnit.value
    : scaleUnit.value;
  for (let value = start; value < max * 1.1; value += scaleUnit.value) {
    scaleList.value.push({
      value: value,
      left: 0
    });
  }
  const cnt = scaleList.value.length;
  if (cnt > 8) {
    scaleUnit.value = scaleUnit.value * 2;
    scaleList.value = scaleList.value.filter((_, i) => (i & 1) === 0);
  } else if (cnt < 4) {
    scaleUnit.value = Math.round(scaleUnit.value / 2);
    scaleList.value = scaleList.value.concat(
      scaleList.value.map(v => ({
        value: v.value - scaleUnit.value,
        left: 0
      }))
    );
  }
  scaleList.value = scaleList.value.filter(
    v => min <= v.value && v.value <= max
  );
  for (const scale of scaleList.value) {
    scale.left = getWidth(scale.value, max, min);
  }
};

const createBar = data => {
  const value = parseFloat(data.value);
  if (!isNaN(value)) {
    const { color, img } = getBarLabelInfo(data);
    const bar = {
      label: data.label,
      value: value,
      color: color,
      img: img,
      size: 10,
      fixed: props.fixed,
      team: data.team
    };
    barList.value.push(bar);
  }
};

const getBarLabelInfo = data => {
  if (data.team) {
    const info = props.labelInfo[data.team];
    if (info) return info;
  }
  if (data.label) {
    const info = props.labelInfo[data.label];
    if (info) return info;
  }
  throw new Error(`Unknown label ${data.label}`);
};

const sortNodeBar = () => {
  instance.value.sort({
    by: element => {
      return getBarValue(element);
    },
    reverse: true
  });
};

const getBarObject = label => {
  return barList.value.find(bar => bar.label === label);
};

// Skipping onUpdated hook since it was causing URI malformed errors
// We'll handle bar updates directly in onMounted

onMounted(() => {
  scaleUnit.value = props.scale;

  instance.value = new Shuffle(document.getElementById("container"), {
    itemSelector: ".item",
    speed: props.shuffleSpeed
  });

  // set initial data
  year.value = props.date[0];
  for (const i in props.stats[0]) {
    const curData = props.stats[0][i];
    curData.value = Number(curData.value);
    createBar(curData);
  }

  sortNodeBar();

  let index = 1;
  setTimeout(() => {
    const loop = setInterval(() => {
      if (index < props.stats.length) {
        year.value = props.date[index];
        const before = {};
        const after = {};
        for (const [i, stat] of props.stats[index].entries()) {
          if (i >= 10) break;
          let prevData = barDict.value[stat.label];
          if (!prevData) {
            prevData = {
              label: stat.label,
              value: nullNumber.value,
              team: stat.team
            };
            createBar(prevData);
          }
          before[stat.label] = prevData.value;
          after[stat.label] = parseFloat(stat.value) || 0;
        }

        before["progress"] = 0;
        after["progress"] = 1;
        new TWEEN.Tween(before)
          .to(after, props.interval * 0.99)
          .easing(TWEEN.Easing.Linear.None)
          .onUpdate(() => {
            for (const label in before) {
              if (label === "progress") {
                progress.value = before["progress"];
              } else {
                const value = before[label];
                getBarObject(label).value = value;
              }
            }
            adjustChart();
          })
          .start();
      } else {
        clearInterval(loop);
      }
      index++;
    }, props.interval);
  }, 3000);

  setInterval(() => {
    sortNodeBar();
    adjustChart();
  }, 100);
});
</script>

<style>
.item-container {
  font-family: sans-serif;
  font-size: 1.25vw;
}
.year {
  position: absolute;
  top: 44vw;
  left: 80vw;
  font-size: 7vw;
  z-index: 20;
  font-weight: 600;
}
.year .progress {
  height: 1.5vw;
  background: rgb(194, 6, 6);
  margin-top: -1vw;
}
.representative {
  background-size: contain;
  background-position: center bottom;
  background-repeat: no-repeat;
  width: 18vw;
  height: 15vw;
  position: absolute;
  top: 29.5vw;
  left: 79vw;
  z-index: 20;
  /* border:1px solid green; */
}
</style>
